baseURL: https://avocados.dev
disablePathToLower: true
languageCode: en-us
title: Developer Avocados
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
permalinks:
  adventcado: /:sections/:month/:day/:filename/
params:
  mainSections: adventcado
  description: Every day in the run-up to Christmas you'll hear from an amazing Avocado. We've asked them to answer five questions about themselves, their origin story, their year and the future. Everyone got to choose their medium so you'll get to read, listen or watch their answers every day.
  images:
    - /img/code-avo.png
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
googleAnalytics: UA-184160606-1
imaging:
  quality: 85
  resampleFilter: Lanczos
